### ISSUE TITLE
Better to add a function set LED transition animation

### ISSUE THREAD

**Issue by caichunjian520** [javl/Instax-BLE#1]
Here is a log data from their app, when send command to the printer, the LED will change color with transition animation, which I think is better than change from one color directly to another. 

`41 62 00 FB 30 01 03 50 08 00 00 00 00 15 00 0E 2A 00 1D 3F 00 2C 54 00 3B 69 00 4A 7E 00 58 93 00 67 A8 00 76 BD 00 85 D3 00 94 CA 00 8C C2 00 85 BA 00 7E B2 00 76 AA 00 6F A2 00 68 9A 00 60 92 00 59 8A 00 52 82 00 4B 8E 00 43 9B 00 3C A7 00 34 B4 00 2D C0 00 25 CD 00 1E D9 00 16 E6 00 0F F2 00 07 FF 00 00 E5 19 00 CC 33 00 B2 4C 00 99 66 00 7F 7F 00 66 99 00 4C B2 00 33 CC 00 19 E5 00 00 FF 00 00 FF 19 00 FF 33 00 FF 4C 00 FF 66 00 FF 7F 00 FF 99 00 FF B2 00 FF CC 00 FF E5 00 FF FF 00 F2 FF 00 E5 FF 00 D8 FF 00 CB FF 00 BE FF 00 B2 FF 00 A5 FF 00 98 FF 00 8B FF 00 7F FF 00 72 FF 00 65 FF 00 58 FF 00 4C FF 00 3F FF 00 32 FF 00 26 FF 00 19 FF 00 0C FF 00 00 FF 02 02 E6 04 04 CD 07 07 B4 09 09 9C 0C 0C 83 0E 0E 6A 10 10 52 13 13 39 15 15 20 4B `

**Comment by javl** [comment]
The light effect in this repo is just an example of how to send the command.
